/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco;

/**
 *
 * @author New2
 */
public class ViewUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewUI
     */
    public ViewUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateralPrincipal = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        menuLateralOperador = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        menuLateralCliente = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        areaCriarBanco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        areaEntrarBanco = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        areaOperador = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        areaCliente = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLateralPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setText("B6");
        menuLateralPrincipal.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jButton16.setText("B1");
        menuLateralPrincipal.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jButton17.setText("B2");
        menuLateralPrincipal.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        jButton18.setText("B3");
        menuLateralPrincipal.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jButton19.setText("B4");
        menuLateralPrincipal.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jButton20.setText("B5");
        menuLateralPrincipal.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, -1));

        getContentPane().add(menuLateralPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 700));

        menuLateralOperador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton27.setText("B6");
        menuLateralOperador.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jButton28.setText("B1");
        menuLateralOperador.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jButton29.setText("B2");
        menuLateralOperador.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        jButton30.setText("B3");
        menuLateralOperador.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jButton31.setText("B4");
        menuLateralOperador.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jButton32.setText("B5");
        menuLateralOperador.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, -1));

        getContentPane().add(menuLateralOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 700));

        menuLateralCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton21.setText("B6");
        menuLateralCliente.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jButton22.setText("B1");
        menuLateralCliente.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jButton23.setText("B2");
        menuLateralCliente.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        jButton24.setText("B3");
        menuLateralCliente.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jButton25.setText("B4");
        menuLateralCliente.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jButton26.setText("B5");
        menuLateralCliente.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, -1));

        getContentPane().add(menuLateralCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 700));

        areaCriarBanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("AAAAAAAAAA");
        areaCriarBanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("AAAAAAAAAA");
        areaCriarBanco.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel3.setText("AAAAAAAAAA");
        areaCriarBanco.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jLabel4.setText("AAAAAAAAAA");
        areaCriarBanco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel5.setText("AAAAAAAAAA");
        areaCriarBanco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jButton7.setText("Confirmar");
        areaCriarBanco.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 166, 170, -1));

        jButton8.setText("Limpar");
        areaCriarBanco.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 166, 170, -1));
        areaCriarBanco.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 775, -1));
        areaCriarBanco.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 42, 775, -1));
        areaCriarBanco.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 73, 775, -1));
        areaCriarBanco.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 104, 775, -1));
        areaCriarBanco.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 135, 775, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("MSG ERRO");
        areaCriarBanco.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 505, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        areaCriarBanco.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 855, 469));

        getContentPane().add(areaCriarBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 680));

        areaEntrarBanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("AAAAAAAAAA");
        areaEntrarBanco.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel8.setText("AAAAAAAAAA");
        areaEntrarBanco.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel9.setText("AAAAAAAAAA");
        areaEntrarBanco.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jLabel10.setText("AAAAAAAAAA");
        areaEntrarBanco.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel11.setText("AAAAAAAAAA");
        areaEntrarBanco.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jButton33.setText("Confirmar");
        areaEntrarBanco.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 166, 170, -1));

        jButton34.setText("Limpar");
        areaEntrarBanco.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 166, 170, -1));
        areaEntrarBanco.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 775, -1));
        areaEntrarBanco.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 42, 775, -1));
        areaEntrarBanco.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 73, 775, -1));
        areaEntrarBanco.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 104, 775, -1));
        areaEntrarBanco.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 135, 775, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("MSG ERRO");
        areaEntrarBanco.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 505, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        areaEntrarBanco.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 855, 469));

        getContentPane().add(areaEntrarBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 680));

        areaOperador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("AAAAAAAAAA");
        areaOperador.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel14.setText("AAAAAAAAAA");
        areaOperador.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel15.setText("AAAAAAAAAA");
        areaOperador.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jLabel16.setText("AAAAAAAAAA");
        areaOperador.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel17.setText("AAAAAAAAAA");
        areaOperador.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jButton35.setText("Confirmar");
        areaOperador.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 166, 170, -1));

        jButton36.setText("Limpar");
        areaOperador.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 166, 170, -1));
        areaOperador.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 775, -1));
        areaOperador.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 42, 775, -1));
        areaOperador.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 73, 775, -1));
        areaOperador.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 104, 775, -1));
        areaOperador.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 135, 775, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("MSG ERRO");
        areaOperador.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 505, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        areaOperador.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 855, 469));

        getContentPane().add(areaOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 680));

        areaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("AAAAAAAAAA");
        areaCliente.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel20.setText("AAAAAAAAAA");
        areaCliente.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel21.setText("AAAAAAAAAA");
        areaCliente.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jLabel22.setText("AAAAAAAAAA");
        areaCliente.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel23.setText("AAAAAAAAAA");
        areaCliente.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jButton37.setText("Confirmar");
        areaCliente.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 166, 170, -1));

        jButton38.setText("Limpar");
        areaCliente.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 166, 170, -1));
        areaCliente.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 775, -1));
        areaCliente.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 42, 775, -1));
        areaCliente.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 73, 775, -1));
        areaCliente.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 104, 775, -1));
        areaCliente.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 135, 775, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("MSG ERRO");
        areaCliente.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 505, -1));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        areaCliente.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 855, 469));

        getContentPane().add(areaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaCliente;
    private javax.swing.JPanel areaCriarBanco;
    private javax.swing.JPanel areaEntrarBanco;
    private javax.swing.JPanel areaOperador;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel menuLateralCliente;
    private javax.swing.JPanel menuLateralOperador;
    private javax.swing.JPanel menuLateralPrincipal;
    private javax.swing.JPanel menuLateralPrincipal1;
    // End of variables declaration//GEN-END:variables
}
